### ISSUE TITLE
Support Pandas 1.5.3?

### ISSUE THREAD

**Issue by HallvardHvidsten** [Tideseed/eptr2#1]
Can this package support Pandas 1.5.3? Can you do a build for Pandas 1.5.3?

**Comment by berkorbay** [comment]
Pandas is actually only required for converting results to data frames via postprocess functions. A version with pandas as an optional requirement is in plans.

**Comment by berkorbay** [comment]
Pandas requirement is now optional with the release 0.4.0. You may check https://github.com/Tideseed/eptr2/releases/tag/v0.4.0
