### ISSUE TITLE
Eptr2 Hakkında

### ISSUE THREAD

**Issue by Ekonometrist** [Tideseed/eptr2#3]
Merhaba öncelikle yapmış olduğunuz proje çok başarılı, tebrik etmek istiyorum. Websitesinde cloudflare Captcha'den dolayı giriş yapamıyorum. Bu çok işime yaradı ama istediğim veriler tam oalrak görünmüyor. Proje ile ilgili çalışmalarınız devam ediyor mu? Gerçek ZamanlI Üretim, Kesinleşmiş Günlük Üretim Planı, Günlük Referans Fiyatı (GRF), SGP Günlük Eşleşme Miktarı, Dengeleme Gazı Fiyatları (DGF), 1 Kodlu İşlemler ve Dengesizlik Sistem verilerini websitesindeki şekli ile görüp tüm verileri Python ile çekmek istiyorum. Yardımcı olabilirseniz sevinirim. İyi çalışmalar.

**Comment by berkorbay** [comment]
Merhaba. Çok teşekkürler. 

Aslında çoğu bilgi ve kullanım README içerisinde var https://github.com/Tideseed/eptr2/blob/main/README.md

Bazı servisler henüz yok. Olanların listesini bu servis ile alabilirsiniz.

```python
available_calls = eptr.get_available_calls()
print(available_calls)
```

**Comment by Ekonometrist** [comment]
Hocam, Gerçek Zamanlı Üretim ve  Kesinleşmiş Günlük Üretim Planı veri setini kod ile çalıştırdığımda tüm veriler gelmiyor. Bu sıkıntıyı nasıl çözebilirim acaba? Birden fazla kaynak var orada hepsinin verisini almak istiyorum ama değerler sıfır olarak geliyor. En azından diğer veri setleri olana kadar bu ikisi konusunda yardımcı olabilir misiniz?
İlginiz için şimdiden teşekkür ederim. İyi çalışmalar

![rt-gen](https://github.com/user-attachments/assets/c500ddda-ef2a-4ac4-988c-91deaa12d49c)

**Comment by berkorbay** [comment]
Buradakiler sadece örnek çalıştırma. Yukarıdaki örnekte pp_id'si 2800 olan bir santralin verisi gelmiş durumda. pp_id parametresini kaldırırsanız bütün üretim gelir.

**Comment by Ekonometrist** [comment]
Çok teşekkürler hocam bilgiler için.
